<?php

namespace AppBundle\Repository;

/**
 * ParcelOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcelOrderRepository extends \Doctrine\ORM\EntityRepository
{
	public function save(ParcelOrderInterface $parcelorder) {
		$em = $this->getEntityManager();
		$em->persist($parcelorder);
		$em->flush();
	}
}
