parameters:
    parcel.class: AppBundle\Entity\Parcel
    parcelorder.class: AppBundle\Entity\ParcelOrder
    addessdata.class: AppBundle\Entity\AddressData

services:
    parcel_form.handler:
        class: AppBundle\Handler\ParcelFormHandler
        arguments: ['@doctrine.orm.entity_manager', %parcel.class%, '@form.factory', 'AppBundle\Form\ParcelType']

    parcelorder_form.handler:
        class: AppBundle\Handler\ParcelOrderFormHandler
        arguments: ['@doctrine.orm.entity_manager', %parcelorder.class%, '@form.factory', 'AppBundle\Form\ParcelOrderType']

    addessdata_form.handler:
        class: AppBundle\Handler\AddressDataFormHandler
        arguments: ['@doctrine.orm.entity_manager', %addessdata.class%, '@form.factory', 'AppBundle\Form\AddressDataType']